server:
  port: 8080
spring:
  redis:
    database: 0
    url: redis://localhost:6379
    host: localhost
    port: 6379
    ssl: false
    timeout: 500
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresql
    username: test
    password: test
    driver-class-name: org.postgresql.Driver